package sqlxgen

import (
	"bytes"
	"fmt"
	"go/types"
	"sort"
	"strings"
)

type ddlDialect uint8

const (
	ddlMySQL ddlDialect = iota + 1
	ddlPostgreSQL
)

func GenerateDDL(packages []*PackageSpec) ([]byte, []byte, error) {
	models := make([]*ModelSpec, 0)
	for _, pkg := range packages {
		models = append(models, pkg.Models...)
	}
	sort.Slice(models, func(i, j int) bool {
		left := models[i].Schema + "." + models[i].Table
		right := models[j].Schema + "." + models[j].Table
		return left < right
	})
	mysql, err := renderDDL(models, ddlMySQL)
	if err != nil {
		return nil, nil, err
	}
	postgres, err := renderDDL(models, ddlPostgreSQL)
	if err != nil {
		return nil, nil, err
	}
	return mysql, postgres, nil
}

func renderDDL(models []*ModelSpec, dialect ddlDialect) ([]byte, error) {
	var output bytes.Buffer
	fmt.Fprintf(&output, "-- Code generated by sqlxgen %s. DO NOT EDIT.\n\n", generatorVersion)
	for _, model := range models {
		if err := renderTable(&output, model, dialect); err != nil {
			return nil, fmt.Errorf("render DDL for %s.%s: %w", model.Package.Path, model.Name, err)
		}
	}
	// 外键和索引在所有表之后创建，避免普通依赖顺序问题。
	for _, model := range models {
		for _, field := range model.Fields {
			if field.References == "" {
				continue
			}
			renderForeignKey(&output, model, field, dialect)
		}
	}
	for _, model := range models {
		renderIndexes(&output, model, dialect)
	}
	return output.Bytes(), nil
}

func renderTable(output *bytes.Buffer, model *ModelSpec, dialect ddlDialect) error {
	fmt.Fprintf(output, "CREATE TABLE %s (\n", quoteDDLTable(dialect, model.Schema, model.Table))
	definitions := make([]string, 0, len(model.Fields)+1)
	for _, field := range model.Fields {
		columnType, err := ddlType(field, dialect)
		if err != nil {
			return fmt.Errorf("field %s: %w", field.GoName, err)
		}
		definition := "  " + quoteDDLIdentifier(dialect, field.Column) + " " + columnType
		if field.Auto {
			if dialect == ddlMySQL {
				definition += " AUTO_INCREMENT"
			} else {
				definition += " GENERATED BY DEFAULT AS IDENTITY"
			}
		}
		if field.Nullable {
			definition += " NULL"
		} else {
			definition += " NOT NULL"
		}
		if field.Default != "" {
			definition += " DEFAULT " + field.Default
		}
		definitions = append(definitions, definition)
	}
	keys := make([]string, 0, len(model.Keys))
	for _, field := range model.Keys {
		keys = append(keys, quoteDDLIdentifier(dialect, field.Column))
	}
	definitions = append(definitions, "  PRIMARY KEY ("+strings.Join(keys, ", ")+")")
	output.WriteString(strings.Join(definitions, ",\n"))
	output.WriteString("\n);\n\n")
	return nil
}

func ddlType(field *FieldSpec, dialect ddlDialect) (string, error) {
	if dialect == ddlMySQL && field.MySQLType != "" {
		return field.MySQLType, nil
	}
	if dialect == ddlPostgreSQL && field.PostgresType != "" {
		return field.PostgresType, nil
	}
	switch field.Kind {
	case FieldString:
		if field.Size > 0 {
			return fmt.Sprintf("VARCHAR(%d)", field.Size), nil
		}
		return "VARCHAR(255)", nil
	case FieldBool:
		if dialect == ddlMySQL {
			return "BOOLEAN", nil
		}
		return "BOOLEAN", nil
	case FieldInteger:
		return integerDDLType(field.ValueType, dialect), nil
	case FieldFloat:
		if field.Precision > 0 {
			return fmt.Sprintf("DECIMAL(%d,%d)", field.Precision, field.Scale), nil
		}
		if basicKind(field.ValueType) == types.Float32 {
			return "REAL", nil
		}
		if dialect == ddlMySQL {
			return "DOUBLE", nil
		}
		return "DOUBLE PRECISION", nil
	case FieldTime:
		if dialect == ddlMySQL {
			return "DATETIME(6)", nil
		}
		return "TIMESTAMPTZ", nil
	case FieldBytes:
		if dialect == ddlMySQL {
			return "BLOB", nil
		}
		return "BYTEA", nil
	case FieldJSON:
		if dialect == ddlMySQL {
			return "JSON", nil
		}
		return "JSONB", nil
	default:
		return "", fmt.Errorf("type %s requires mysql_type and postgres_type overrides", types.TypeString(field.ValueType, packagePathQualifier))
	}
}

func integerDDLType(typ types.Type, dialect ddlDialect) string {
	kind := basicKind(typ)
	if dialect == ddlMySQL {
		base := "BIGINT"
		switch kind {
		case types.Int8, types.Uint8:
			base = "TINYINT"
		case types.Int16, types.Uint16:
			base = "SMALLINT"
		case types.Int32, types.Uint32:
			base = "INTEGER"
		}
		if isUnsigned(kind) {
			base += " UNSIGNED"
		}
		return base
	}
	switch kind {
	case types.Int8, types.Int16, types.Uint8:
		return "SMALLINT"
	case types.Int32, types.Uint16:
		return "INTEGER"
	case types.Uint32, types.Int, types.Int64:
		return "BIGINT"
	case types.Uint, types.Uint64, types.Uintptr:
		return "NUMERIC(20,0)"
	default:
		return "BIGINT"
	}
}

func isUnsigned(kind types.BasicKind) bool {
	return kind == types.Uint || kind == types.Uint8 || kind == types.Uint16 || kind == types.Uint32 || kind == types.Uint64 || kind == types.Uintptr
}

func basicKind(typ types.Type) types.BasicKind {
	if named, ok := typ.(*types.Named); ok {
		typ = named.Underlying()
	}
	if basic, ok := typ.(*types.Basic); ok {
		return basic.Kind()
	}
	return types.Invalid
}

func renderForeignKey(output *bytes.Buffer, model *ModelSpec, field *FieldSpec, dialect ddlDialect) {
	table, columnPart, _ := strings.Cut(field.References, "(")
	column := strings.TrimSuffix(columnPart, ")")
	parts := strings.Split(table, ".")
	refSchema := ""
	refTable := parts[0]
	if len(parts) == 2 {
		refSchema, refTable = parts[0], parts[1]
	}
	constraint := "fk_" + model.Table + "_" + field.Column
	fmt.Fprintf(output, "ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		quoteDDLTable(dialect, model.Schema, model.Table), quoteDDLIdentifier(dialect, constraint),
		quoteDDLIdentifier(dialect, field.Column), quoteDDLTable(dialect, refSchema, refTable), quoteDDLIdentifier(dialect, column))
	if field.OnDelete != "" {
		fmt.Fprintf(output, " ON DELETE %s", field.OnDelete)
	}
	output.WriteString(";\n")
}

func renderIndexes(output *bytes.Buffer, model *ModelSpec, dialect ddlDialect) {
	type indexSpec struct {
		name    string
		unique  bool
		columns []string
	}
	indexes := make(map[string]*indexSpec)
	for _, field := range model.Fields {
		for _, item := range []struct {
			name   string
			unique bool
		}{{field.Index, false}, {field.Unique, true}} {
			if item.name == "" {
				continue
			}
			entry := indexes[item.name]
			if entry == nil {
				entry = &indexSpec{name: item.name, unique: item.unique}
				indexes[item.name] = entry
			}
			entry.columns = append(entry.columns, field.Column)
		}
	}
	names := make([]string, 0, len(indexes))
	for name := range indexes {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		index := indexes[name]
		columns := make([]string, len(index.columns))
		for position, column := range index.columns {
			columns[position] = quoteDDLIdentifier(dialect, column)
		}
		unique := ""
		if index.unique {
			unique = "UNIQUE "
		}
		fmt.Fprintf(output, "CREATE %sINDEX %s ON %s (%s);\n", unique, quoteDDLIdentifier(dialect, index.name),
			quoteDDLTable(dialect, model.Schema, model.Table), strings.Join(columns, ", "))
	}
	if len(names) > 0 {
		output.WriteByte('\n')
	}
}

func quoteDDLIdentifier(dialect ddlDialect, identifier string) string {
	if dialect == ddlMySQL {
		return "`" + identifier + "`"
	}
	return `"` + identifier + `"`
}

func quoteDDLTable(dialect ddlDialect, schema, table string) string {
	if schema == "" {
		return quoteDDLIdentifier(dialect, table)
	}
	return quoteDDLIdentifier(dialect, schema) + "." + quoteDDLIdentifier(dialect, table)
}
