package sqlxgen

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

func TestGenerateBasicFixture(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	config := GenerateConfig{Dir: root, Patterns: []string{"./internal/sqlxgen/testdata/basic"}}
	result, err := Generate(config)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(result.Packages) != 1 || len(result.Packages[0].Models) != 2 || len(result.Packages[0].CustomQueries) != 1 {
		t.Fatalf("unexpected scan result: %#v", result.Packages)
	}
	assertContains(t, string(result.MySQLDDL), "`id` BIGINT AUTO_INCREMENT NOT NULL")
	assertContains(t, string(result.PGDDL), `"id" BIGINT GENERATED BY ALWAYS AS IDENTITY NOT NULL`)
	assertContains(t, string(result.PGDDL), `FOREIGN KEY ("user_id") REFERENCES "app"."users" ("id") ON DELETE CASCADE`)

	source, err := GenerateGo(result.Packages[0])
	if err != nil {
		t.Fatalf("GenerateGo() error = %v", err)
	}
	assertContains(t, string(source), "func (d *UserDAO) Create")
	assertContains(t, string(source), "func NewUserCustomQueries")
	assertContains(t, string(source), "func (d *MembershipDAO) GetByKey")
	assertContains(t, string(source), "var builder strings.Builder")
	secondSource, err := GenerateGo(result.Packages[0])
	if err != nil || !bytes.Equal(source, secondSource) {
		t.Fatalf("generated Go source is not deterministic: %v", err)
	}

	// 通过 overlay 让 go/packages 对尚未落盘的生成文件执行真实类型检查。
	generatedPath := filepath.Join(result.Packages[0].Dir, generatedFileName)
	loaded, err := packages.Load(&packages.Config{
		Dir: root,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedDeps,
		Overlay: map[string][]byte{generatedPath: source},
	}, "./internal/sqlxgen/testdata/basic")
	if err != nil {
		t.Fatalf("load generated fixture: %v", err)
	}
	if packages.PrintErrors(loaded) > 0 {
		t.Fatal("generated fixture failed type checking")
	}
}

func TestScanRejectsPointerModelAndParameterMismatch(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	_, err = Scan(GenerateConfig{Dir: root, Patterns: []string{"./internal/sqlxgen/testdata/invalid"}})
	if err == nil || !strings.Contains(err.Error(), "non-pointer") {
		t.Fatalf("pointer marker error = %v", err)
	}
	_, err = Scan(GenerateConfig{Dir: root, Patterns: []string{"./internal/sqlxgen/testdata/invalidquery"}})
	if err == nil || !strings.Contains(err.Error(), "do not match") {
		t.Fatalf("parameter mismatch error = %v", err)
	}
}

func TestGenerateCustomOnlyPackage(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	result, err := Generate(GenerateConfig{Dir: root, Patterns: []string{"./internal/sqlxgen/testdata/customonly"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Packages) != 1 || len(result.Packages[0].Models) != 0 {
		t.Fatalf("unexpected custom-only result: %#v", result.Packages)
	}
	source, err := GenerateGo(result.Packages[0])
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(source), `"fmt"`) || strings.Contains(string(source), `"strings"`) || strings.Contains(string(source), `"github.com/jmoiron/sqlx"`) {
		t.Fatalf("custom exec-only source has unused imports:\n%s", source)
	}
	generatedPath := filepath.Join(result.Packages[0].Dir, generatedFileName)
	loaded, err := packages.Load(&packages.Config{
		Dir: root,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedDeps,
		Overlay: map[string][]byte{generatedPath: source},
	}, "./internal/sqlxgen/testdata/customonly")
	if err != nil || packages.PrintErrors(loaded) > 0 {
		t.Fatalf("custom-only generated package failed type checking: %v", err)
	}
}

func TestNamedParametersSkipQuotesCommentsAndCasts(t *testing.T) {
	parameters, err := namedParameters(`SELECT ':ignored', value::text
		FROM t /* :ignored */ WHERE id = :id -- :ignored
		AND name = :name`)
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Join(sortedSet(parameters), ","); got != "id,name" {
		t.Fatalf("parameters = %q", got)
	}
}

func assertContains(t *testing.T, value, expected string) {
	t.Helper()
	if !strings.Contains(value, expected) {
		t.Fatalf("expected output to contain %q\n%s", expected, value)
	}
}
