package sqlxgen

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"
)

type sourceRenderer struct {
	pkg     *PackageSpec
	imports map[string]string
	used    map[string]string
	body    bytes.Buffer
}

func newSourceRenderer(pkg *PackageSpec) *sourceRenderer {
	r := &sourceRenderer{pkg: pkg, imports: make(map[string]string), used: make(map[string]string)}
	baseImports := []struct{ path, alias string }{{"context", "context"}, {runtimePackagePath, "sqlxgen"}}
	if len(pkg.Models) > 0 {
		baseImports = append(baseImports,
			struct{ path, alias string }{"fmt", "fmt"},
			struct{ path, alias string }{"strings", "strings"},
			struct{ path, alias string }{"github.com/jmoiron/sqlx", "sqlx"},
		)
	}
	for _, query := range pkg.CustomQueries {
		for _, method := range query.Methods {
			if method.Mode == CustomOne || method.Mode == CustomMany {
				baseImports = append(baseImports, struct{ path, alias string }{"github.com/jmoiron/sqlx", "sqlx"})
			}
		}
	}
	for _, item := range baseImports {
		r.imports[item.path] = item.alias
		r.used[item.alias] = item.path
	}
	return r
}

func GenerateGo(pkg *PackageSpec) ([]byte, error) {
	renderer := newSourceRenderer(pkg)
	if len(pkg.Models) > 0 {
		renderer.renderQueries()
		for _, model := range pkg.Models {
			renderer.renderModel(model)
		}
	}
	for _, query := range pkg.CustomQueries {
		renderer.renderCustomQuery(query)
	}
	var source bytes.Buffer
	fmt.Fprintf(&source, "// Code generated by sqlxgen %s. DO NOT EDIT.\n\n", generatorVersion)
	fmt.Fprintf(&source, "package %s\n\n", pkg.Name)
	source.WriteString("import (\n")
	paths := make([]string, 0, len(renderer.imports))
	for path := range renderer.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		alias := renderer.imports[path]
		defaultAlias := strings.TrimSuffix(path[strings.LastIndex(path, "/")+1:], ".go")
		if alias == defaultAlias {
			fmt.Fprintf(&source, "\t%q\n", path)
		} else {
			fmt.Fprintf(&source, "\t%s %q\n", alias, path)
		}
	}
	source.WriteString(")\n\n")
	source.Write(renderer.body.Bytes())
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source for %s: %w\n%s", pkg.Path, err, source.String())
	}
	return formatted, nil
}

func (r *sourceRenderer) typeName(typ types.Type) string {
	return types.TypeString(typ, func(pkg *types.Package) string {
		if pkg == nil || pkg.Path() == r.pkg.Path {
			return ""
		}
		if alias, ok := r.imports[pkg.Path()]; ok {
			return alias
		}
		alias := pkg.Name()
		if existing, exists := r.used[alias]; exists && existing != pkg.Path() {
			for suffix := 2; ; suffix++ {
				candidate := fmt.Sprintf("%s%d", alias, suffix)
				if _, used := r.used[candidate]; !used {
					alias = candidate
					break
				}
			}
		}
		r.imports[pkg.Path()] = alias
		r.used[alias] = pkg.Path()
		return alias
	})
}

func (r *sourceRenderer) renderQueries() {
	b := &r.body
	b.WriteString("// Queries 聚合当前包中所有生成的模型查询。\n")
	b.WriteString("type Queries struct {\n\texec sqlxgen.Executor\n")
	for _, model := range r.pkg.Models {
		fmt.Fprintf(b, "\t%s *%sDAO\n", model.Name, model.Name)
	}
	b.WriteString("}\n\n")
	b.WriteString("// NewQueries 使用 DB 或 Tx 创建生成查询入口。\n")
	b.WriteString("func NewQueries(exec sqlxgen.Executor) *Queries {\n\tqueries := &Queries{exec: exec}\n")
	for _, model := range r.pkg.Models {
		fmt.Fprintf(b, "\tqueries.%s = new%sDAO(exec)\n", model.Name, model.Name)
	}
	b.WriteString("\treturn queries\n}\n\n")
	b.WriteString("// With 为同一组查询替换执行器，常用于切换到事务。\n")
	b.WriteString("func (q *Queries) With(exec sqlxgen.Executor) *Queries { return NewQueries(exec) }\n\n")
	b.WriteString("// Executor 返回底层执行器，便于与原生 SQLx 混用。\n")
	b.WriteString("func (q *Queries) Executor() sqlxgen.Executor {\n\tif q == nil { return nil }; return q.exec\n}\n\n")
}

func (r *sourceRenderer) renderModel(model *ModelSpec) {
	r.renderCreateOptions(model)
	r.renderDAO(model)
	r.renderQueryBuilder(model)
	r.renderCreate(model)
	r.renderPrimaryKeyMethods(model)
}

func (r *sourceRenderer) renderCreateOptions(model *ModelSpec) {
	b := &r.body
	fmt.Fprintf(b, "// %sCreateOption 配置 %s 的插入行为。\n", model.Name, model.Name)
	fmt.Fprintf(b, "type %sCreateOption interface { apply%sCreate(map[string]struct{}) }\n\n", model.Name, model.Name)
	fmt.Fprintf(b, "type %sUseDefault struct { column string }\n", lowerFirst(model.Name))
	fmt.Fprintf(b, "func (o %sUseDefault) apply%sCreate(columns map[string]struct{}) { columns[o.column] = struct{}{} }\n\n", lowerFirst(model.Name), model.Name)
	for _, field := range model.Fields {
		if field.Default == "" || field.Auto {
			continue
		}
		baseType, constructor := r.columnDeclaration(field)
		wrapper := lowerFirst(model.Name) + field.GoName + "Column"
		fmt.Fprintf(b, "type %s struct { %s }\n", wrapper, baseType)
		fmt.Fprintf(b, "// UseDefault 使本次插入使用列 %s 的数据库默认值。\n", field.Column)
		fmt.Fprintf(b, "func (c %s) UseDefault() %sCreateOption { return %sUseDefault{column: %q} }\n\n",
			wrapper, model.Name, lowerFirst(model.Name), field.Column)
		_ = constructor
	}
}

func (r *sourceRenderer) renderDAO(model *ModelSpec) {
	b := &r.body
	fmt.Fprintf(b, "// %sDAO 提供 %s 的强类型数据库操作。\n", model.Name, model.Name)
	fmt.Fprintf(b, "type %sDAO struct {\n\texec sqlxgen.Executor\n", model.Name)
	for _, field := range model.Fields {
		columnType, _ := r.columnDeclaration(field)
		if field.Default != "" && !field.Auto {
			columnType = lowerFirst(model.Name) + field.GoName + "Column"
		}
		fmt.Fprintf(b, "\t%s %s\n", field.GoName, columnType)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func new%sDAO(exec sqlxgen.Executor) *%sDAO {\n", model.Name, model.Name)
	fmt.Fprintf(b, "\treturn &%sDAO{exec: exec,\n", model.Name)
	for _, field := range model.Fields {
		columnType, constructor := r.columnDeclaration(field)
		if field.Default != "" && !field.Auto {
			wrapper := lowerFirst(model.Name) + field.GoName + "Column"
			fmt.Fprintf(b, "\t\t%s: %s{%s: %s},\n", field.GoName, wrapper, embeddedTypeName(columnType), constructor)
		} else {
			fmt.Fprintf(b, "\t\t%s: %s,\n", field.GoName, constructor)
		}
	}
	b.WriteString("\t}\n}\n\n")
	fmt.Fprintf(b, "var %sAllowedColumns = map[string]struct{}{\n", lowerFirst(model.Name))
	for _, field := range model.Fields {
		fmt.Fprintf(b, "\tsqlxgen.ColumnKey(%q, %q): {},\n", field.Owner, field.Column)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "var %sDefaultColumns = map[string]struct{}{\n", lowerFirst(model.Name))
	for _, field := range model.Fields {
		if field.Default != "" && !field.Auto {
			fmt.Fprintf(b, "\t%q: {},\n", field.Column)
		}
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (d *%sDAO) table(dialect sqlxgen.Dialect) string { return sqlxgen.QuoteTable(dialect, %q, %q) }\n", model.Name, model.Schema, model.Table)
	fmt.Fprintf(b, "func (d *%sDAO) selectColumns(dialect sqlxgen.Dialect) string {\n", model.Name)
	fmt.Fprintf(b, "\tvar builder strings.Builder; builder.Grow(%d)\n", len(model.Fields)*16)
	for index, field := range model.Fields {
		if index > 0 {
			b.WriteString("\tbuilder.WriteString(\", \")\n")
		}
		fmt.Fprintf(b, "\tbuilder.WriteString(sqlxgen.QuoteIdentifier(dialect, %q))\n", field.Column)
	}
	b.WriteString("\treturn builder.String()\n}\n\n")
}

func (r *sourceRenderer) columnDeclaration(field *FieldSpec) (string, string) {
	prefix := ""
	if field.Nullable {
		prefix = "Nullable"
	}
	var generic string
	var constructor string
	switch field.Kind {
	case FieldInteger, FieldFloat:
		typeName := r.typeName(field.ValueType)
		generic = fmt.Sprintf("sqlxgen.%sNumericColumn[%s]", prefix, typeName)
		constructor = fmt.Sprintf("sqlxgen.New%sNumericColumn[%s](%q, %q)", prefix, typeName, field.Column, field.Owner)
	case FieldString:
		typeName := r.typeName(field.ValueType)
		generic = fmt.Sprintf("sqlxgen.%sStringColumn[%s]", prefix, typeName)
		constructor = fmt.Sprintf("sqlxgen.New%sStringColumn[%s](%q, %q)", prefix, typeName, field.Column, field.Owner)
	case FieldTime:
		generic = "sqlxgen." + prefix + "TimeColumn"
		constructor = fmt.Sprintf("sqlxgen.New%sTimeColumn(%q, %q)", prefix, field.Column, field.Owner)
	default:
		typeName := r.typeName(field.ValueType)
		generic = fmt.Sprintf("sqlxgen.%sColumn[%s]", prefix, typeName)
		constructor = fmt.Sprintf("sqlxgen.New%sColumn[%s](%q, %q)", prefix, typeName, field.Column, field.Owner)
	}
	return generic, constructor
}

func embeddedTypeName(typ string) string {
	if index := strings.Index(typ, "["); index >= 0 {
		name := typ[:index]
		return name[strings.LastIndex(name, ".")+1:]
	}
	return typ[strings.LastIndex(typ, ".")+1:]
}

func (r *sourceRenderer) renderQueryBuilder(model *ModelSpec) {
	b := &r.body
	queryType := model.Name + "Query"
	fmt.Fprintf(b, "// %s 是不可变的 %s 查询构造器。\n", queryType, model.Name)
	fmt.Fprintf(b, "type %s struct {\n\tdao *%sDAO\n\tpredicates []sqlxgen.Expr\n\torders []sqlxgen.Order\n\tlimit *int\n\toffset *int\n\tallowAll bool\n}\n\n", queryType, model.Name)
	fmt.Fprintf(b, "func (d *%sDAO) query() %s { return %s{dao: d} }\n", model.Name, queryType, queryType)
	fmt.Fprintf(b, "func (d *%sDAO) Where(exprs ...sqlxgen.Expr) %s { return d.query().Where(exprs...) }\n", model.Name, queryType)
	fmt.Fprintf(b, "func (d *%sDAO) Order(orders ...sqlxgen.Order) %s { return d.query().Order(orders...) }\n", model.Name, queryType)
	fmt.Fprintf(b, "func (d *%sDAO) Limit(limit int) %s { return d.query().Limit(limit) }\n", model.Name, queryType)
	fmt.Fprintf(b, "func (d *%sDAO) AllowAll() %s { return d.query().AllowAll() }\n\n", model.Name, queryType)
	fmt.Fprintf(b, "func (q %s) Where(exprs ...sqlxgen.Expr) %s { q.predicates = append(append([]sqlxgen.Expr(nil), q.predicates...), exprs...); return q }\n", queryType, queryType)
	fmt.Fprintf(b, "func (q %s) Order(orders ...sqlxgen.Order) %s { q.orders = append(append([]sqlxgen.Order(nil), q.orders...), orders...); return q }\n", queryType, queryType)
	fmt.Fprintf(b, "func (q %s) Limit(limit int) %s { q.limit = &limit; return q }\n", queryType, queryType)
	fmt.Fprintf(b, "func (q %s) Offset(offset int) %s { q.offset = &offset; return q }\n", queryType, queryType)
	fmt.Fprintf(b, "func (q %s) AllowAll() %s { q.allowAll = true; return q }\n\n", queryType, queryType)

	fmt.Fprintf(b, "func (q %s) selectSQL() (string, []any, error) {\n", queryType)
	b.WriteString("\tif q.dao == nil { return \"\", nil, fmt.Errorf(\"sqlxgen: query DAO is nil\") }\n")
	b.WriteString("\tdialect, err := sqlxgen.DetectDialect(q.dao.exec); if err != nil { return \"\", nil, err }\n")
	fmt.Fprintf(b, "\twhere, args, err := sqlxgen.BuildWhere(dialect, q.predicates, %sAllowedColumns); if err != nil { return \"\", nil, err }\n", lowerFirst(model.Name))
	fmt.Fprintf(b, "\torder, err := sqlxgen.BuildOrder(dialect, q.orders, %sAllowedColumns); if err != nil { return \"\", nil, err }\n", lowerFirst(model.Name))
	b.WriteString("\tpagination, pageArgs, err := sqlxgen.BuildPagination(dialect, q.limit, q.offset); if err != nil { return \"\", nil, err }\n")
	b.WriteString("\tcolumns, table := q.dao.selectColumns(dialect), q.dao.table(dialect); var builder strings.Builder; builder.Grow(len(columns) + len(table) + len(where) + len(order) + len(pagination) + 13)\n")
	b.WriteString("\tbuilder.WriteString(\"SELECT \"); builder.WriteString(columns); builder.WriteString(\" FROM \"); builder.WriteString(table); builder.WriteString(where); builder.WriteString(order); builder.WriteString(pagination)\n")
	b.WriteString("\treturn q.dao.exec.Rebind(builder.String()), append(args, pageArgs...), nil\n}\n\n")

	fmt.Fprintf(b, "func (q %s) First(ctx context.Context) (*%s, error) {\n", queryType, model.Name)
	b.WriteString("\tlimit := 1; q.limit = &limit\n\tquery, args, err := q.selectSQL(); if err != nil { return nil, err }\n")
	fmt.Fprintf(b, "\tvar result %s\n\tif err := sqlx.GetContext(ctx, q.dao.exec, &result, query, args...); err != nil { return nil, err }; return &result, nil\n}\n\n", model.Name)
	fmt.Fprintf(b, "func (q %s) All(ctx context.Context) ([]%s, error) {\n", queryType, model.Name)
	b.WriteString("\tquery, args, err := q.selectSQL(); if err != nil { return nil, err }\n")
	fmt.Fprintf(b, "\tvar result []%s\n\tif err := sqlx.SelectContext(ctx, q.dao.exec, &result, query, args...); err != nil { return nil, err }; return result, nil\n}\n\n", model.Name)
	fmt.Fprintf(b, "func (q %s) Count(ctx context.Context) (int64, error) {\n", queryType)
	b.WriteString("\tif q.dao == nil { return 0, fmt.Errorf(\"sqlxgen: query DAO is nil\") }; dialect, err := sqlxgen.DetectDialect(q.dao.exec); if err != nil { return 0, err }\n")
	fmt.Fprintf(b, "\twhere, args, err := sqlxgen.BuildWhere(dialect, q.predicates, %sAllowedColumns); if err != nil { return 0, err }\n", lowerFirst(model.Name))
	b.WriteString("\ttable := q.dao.table(dialect); var builder strings.Builder; builder.Grow(len(table) + len(where) + 21); builder.WriteString(\"SELECT COUNT(*) FROM \"); builder.WriteString(table); builder.WriteString(where); query := q.dao.exec.Rebind(builder.String()); var result int64\n")
	b.WriteString("\tif err := sqlx.GetContext(ctx, q.dao.exec, &result, query, args...); err != nil { return 0, err }; return result, nil\n}\n\n")
	fmt.Fprintf(b, "func (q %s) Exists(ctx context.Context) (bool, error) {\n", queryType)
	b.WriteString("\tif q.dao == nil { return false, fmt.Errorf(\"sqlxgen: query DAO is nil\") }; dialect, err := sqlxgen.DetectDialect(q.dao.exec); if err != nil { return false, err }\n")
	fmt.Fprintf(b, "\twhere, args, err := sqlxgen.BuildWhere(dialect, q.predicates, %sAllowedColumns); if err != nil { return false, err }\n", lowerFirst(model.Name))
	b.WriteString("\ttable := q.dao.table(dialect); var builder strings.Builder; builder.Grow(len(table) + len(where) + 30); builder.WriteString(\"SELECT EXISTS(SELECT 1 FROM \"); builder.WriteString(table); builder.WriteString(where); builder.WriteByte(')'); query := q.dao.exec.Rebind(builder.String()); var result bool\n")
	b.WriteString("\tif err := sqlx.GetContext(ctx, q.dao.exec, &result, query, args...); err != nil { return false, err }; return result, nil\n}\n\n")

	fmt.Fprintf(b, "func (q %s) Update(ctx context.Context, assignments ...sqlxgen.Assignment) (int64, error) {\n", queryType)
	b.WriteString("\tif q.dao == nil { return 0, fmt.Errorf(\"sqlxgen: query DAO is nil\") }; if sqlxgen.IsUnrestricted(q.predicates) && !q.allowAll { return 0, sqlxgen.ErrUnsafeMutation }\n")
	b.WriteString("\tdialect, err := sqlxgen.DetectDialect(q.dao.exec); if err != nil { return 0, err }\n")
	fmt.Fprintf(b, "\tset, args, err := sqlxgen.BuildAssignments(dialect, assignments, %sAllowedColumns); if err != nil { return 0, err }\n", lowerFirst(model.Name))
	fmt.Fprintf(b, "\twhere, whereArgs, err := sqlxgen.BuildWhere(dialect, q.predicates, %sAllowedColumns); if err != nil { return 0, err }; args = append(args, whereArgs...)\n", lowerFirst(model.Name))
	b.WriteString("\ttable := q.dao.table(dialect); var builder strings.Builder; builder.Grow(len(table) + len(set) + len(where) + 12); builder.WriteString(\"UPDATE \"); builder.WriteString(table); builder.WriteString(\" SET \"); builder.WriteString(set); builder.WriteString(where); query := q.dao.exec.Rebind(builder.String()); result, err := q.dao.exec.ExecContext(ctx, query, args...); if err != nil { return 0, err }; return result.RowsAffected()\n}\n\n")
	fmt.Fprintf(b, "func (q %s) Delete(ctx context.Context) (int64, error) {\n", queryType)
	b.WriteString("\tif q.dao == nil { return 0, fmt.Errorf(\"sqlxgen: query DAO is nil\") }; if sqlxgen.IsUnrestricted(q.predicates) && !q.allowAll { return 0, sqlxgen.ErrUnsafeMutation }\n")
	b.WriteString("\tdialect, err := sqlxgen.DetectDialect(q.dao.exec); if err != nil { return 0, err }\n")
	fmt.Fprintf(b, "\twhere, args, err := sqlxgen.BuildWhere(dialect, q.predicates, %sAllowedColumns); if err != nil { return 0, err }\n", lowerFirst(model.Name))
	b.WriteString("\ttable := q.dao.table(dialect); var builder strings.Builder; builder.Grow(len(table) + len(where) + 12); builder.WriteString(\"DELETE FROM \"); builder.WriteString(table); builder.WriteString(where); query := q.dao.exec.Rebind(builder.String()); result, err := q.dao.exec.ExecContext(ctx, query, args...); if err != nil { return 0, err }; return result.RowsAffected()\n}\n\n")
}

func (r *sourceRenderer) renderCreate(model *ModelSpec) {
	b := &r.body
	fmt.Fprintf(b, "func (d *%sDAO) Create(ctx context.Context, value *%s, options ...%sCreateOption) error {\n", model.Name, model.Name, model.Name)
	b.WriteString("\tif d == nil || value == nil { return fmt.Errorf(\"%w: DAO and value must not be nil\", sqlxgen.ErrInvalidArgument) }; dialect, err := sqlxgen.DetectDialect(d.exec); if err != nil { return err }\n")
	b.WriteString("\tdefaults := make(map[string]struct{}, len(options)); for _, option := range options { if option == nil { return fmt.Errorf(\"%w: create option is nil\", sqlxgen.ErrInvalidArgument) }; option.apply")
	b.WriteString(model.Name)
	b.WriteString("Create(defaults) }\n")
	fmt.Fprintf(b, "\tfor column := range defaults { if _, ok := %sDefaultColumns[column]; !ok { return fmt.Errorf(\"%%w: column %%q has no database default\", sqlxgen.ErrInvalidArgument, column) } }\n", lowerFirst(model.Name))
	fmt.Fprintf(b, "\tvar columns, placeholders strings.Builder; columns.Grow(%d); placeholders.Grow(%d); columnCount := 0; args := make([]any, 0, %d)\n", len(model.Fields)*16, len(model.Fields)*3, len(model.Fields))
	for _, field := range model.Fields {
		if field.Auto {
			continue
		}
		if field.Default != "" {
			fmt.Fprintf(b, "\tif _, useDefault := defaults[%q]; !useDefault {\n", field.Column)
		}
		b.WriteString("\t\tif columnCount > 0 { columns.WriteString(\", \"); placeholders.WriteString(\", \") }\n")
		fmt.Fprintf(b, "\t\tcolumns.WriteString(sqlxgen.QuoteIdentifier(dialect, %q)); placeholders.WriteByte('?'); columnCount++; args = append(args, value.%s)\n", field.Column, field.Access)
		if field.Default != "" {
			b.WriteString("\t}\n")
		}
	}
	b.WriteString("\ttable := d.table(dialect); var builder strings.Builder; builder.Grow(len(table) + columns.Len() + placeholders.Len() + 32); builder.WriteString(\"INSERT INTO \"); builder.WriteString(table)\n")
	b.WriteString("\tif columnCount == 0 { if dialect == sqlxgen.DialectMySQL { builder.WriteString(\" () VALUES ()\") } else { builder.WriteString(\" DEFAULT VALUES\") } } else { builder.WriteString(\" (\"); builder.WriteString(columns.String()); builder.WriteString(\") VALUES (\"); builder.WriteString(placeholders.String()); builder.WriteByte(')') }\n")
	if model.Auto != nil {
		fmt.Fprintf(b, "\tif dialect == sqlxgen.DialectPostgreSQL { builder.WriteString(\" RETURNING \"); builder.WriteString(sqlxgen.QuoteIdentifier(dialect, %q)); return d.exec.QueryRowxContext(ctx, d.exec.Rebind(builder.String()), args...).Scan(&value.%s) }\n", model.Auto.Column, model.Auto.Access)
		b.WriteString("\tresult, err := d.exec.ExecContext(ctx, d.exec.Rebind(builder.String()), args...); if err != nil { return err }; id, err := result.LastInsertId(); if err != nil { return err }; return sqlxgen.AssignAutoID(&value.")
		b.WriteString(model.Auto.Access)
		b.WriteString(", id)\n}\n\n")
	} else {
		b.WriteString("\t_, err = d.exec.ExecContext(ctx, d.exec.Rebind(builder.String()), args...); return err\n}\n\n")
	}
	fmt.Fprintf(b, "func (d *%sDAO) Reload(ctx context.Context, value *%s) error {\n", model.Name, model.Name)
	b.WriteString("\tif value == nil { return fmt.Errorf(\"%w: value is nil\", sqlxgen.ErrInvalidArgument) }\n")
	call := r.primaryGetCall(model, "d", "value.")
	fmt.Fprintf(b, "\tfresh, err := %s; if err != nil { return err }; *value = *fresh; return nil\n}\n\n", call)
}

func (r *sourceRenderer) renderPrimaryKeyMethods(model *ModelSpec) {
	b := &r.body
	if len(model.Keys) == 1 {
		key := model.Keys[0]
		methodSuffix := key.GoName
		fmt.Fprintf(b, "func (d *%sDAO) GetBy%s(ctx context.Context, value %s) (*%s, error) { return d.Where(d.%s.Eq(value)).First(ctx) }\n", model.Name, methodSuffix, r.typeName(key.ValueType), model.Name, key.GoName)
		fmt.Fprintf(b, "func (d *%sDAO) UpdateBy%s(ctx context.Context, value %s, assignments ...sqlxgen.Assignment) (int64, error) { return d.Where(d.%s.Eq(value)).Update(ctx, assignments...) }\n", model.Name, methodSuffix, r.typeName(key.ValueType), key.GoName)
		fmt.Fprintf(b, "func (d *%sDAO) DeleteBy%s(ctx context.Context, value %s) (int64, error) { return d.Where(d.%s.Eq(value)).Delete(ctx) }\n\n", model.Name, methodSuffix, r.typeName(key.ValueType), key.GoName)
		return
	}
	fmt.Fprintf(b, "// %sKey 是 %s 的联合主键。\n", model.Name, model.Name)
	fmt.Fprintf(b, "type %sKey struct {\n", model.Name)
	for _, key := range model.Keys {
		fmt.Fprintf(b, "\t%s %s\n", key.GoName, r.typeName(key.ValueType))
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "func (d *%sDAO) GetByKey(ctx context.Context, key %sKey) (*%s, error) { return d.Where(", model.Name, model.Name, model.Name)
	for index, key := range model.Keys {
		if index > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "d.%s.Eq(key.%s)", key.GoName, key.GoName)
	}
	b.WriteString(").First(ctx) }\n")
	fmt.Fprintf(b, "func (d *%sDAO) UpdateByKey(ctx context.Context, key %sKey, assignments ...sqlxgen.Assignment) (int64, error) { return d.Where(", model.Name, model.Name)
	for index, key := range model.Keys {
		if index > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "d.%s.Eq(key.%s)", key.GoName, key.GoName)
	}
	b.WriteString(").Update(ctx, assignments...) }\n")
	fmt.Fprintf(b, "func (d *%sDAO) DeleteByKey(ctx context.Context, key %sKey) (int64, error) { return d.Where(", model.Name, model.Name)
	for index, key := range model.Keys {
		if index > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "d.%s.Eq(key.%s)", key.GoName, key.GoName)
	}
	b.WriteString(").Delete(ctx) }\n\n")
}

func (r *sourceRenderer) primaryGetCall(model *ModelSpec, receiver, prefix string) string {
	if len(model.Keys) == 1 {
		return fmt.Sprintf("%s.GetBy%s(ctx, %s%s)", receiver, model.Keys[0].GoName, prefix, model.Keys[0].Access)
	}
	var fields []string
	for _, key := range model.Keys {
		fields = append(fields, fmt.Sprintf("%s: %s%s", key.GoName, prefix, key.Access))
	}
	return fmt.Sprintf("%s.GetByKey(ctx, %sKey{%s})", receiver, model.Name, strings.Join(fields, ", "))
}

func (r *sourceRenderer) renderCustomQuery(query *CustomQuerySpec) {
	b := &r.body
	implementation := lowerFirst(query.Name) + "Impl"
	fmt.Fprintf(b, "type %s struct { exec sqlxgen.Executor }\n\n", implementation)
	fmt.Fprintf(b, "// New%s 创建自定义 SQL 查询实现。\n", query.Name)
	fmt.Fprintf(b, "func New%s(exec sqlxgen.Executor) %s { return &%s{exec: exec} }\n\n", query.Name, query.Name, implementation)
	for _, method := range query.Methods {
		r.renderCustomMethod(implementation, method)
	}
}

func (r *sourceRenderer) renderCustomMethod(implementation string, method *CustomMethodSpec) {
	b := &r.body
	param := ""
	if method.ParamType != nil {
		param = ", arg " + r.typeName(method.ParamType)
	}
	result := "error"
	switch method.Mode {
	case CustomRowsAffected:
		result = "(int64, error)"
	case CustomMany:
		result = "([]" + r.typeName(method.ResultType) + ", error)"
	case CustomOne:
		prefix := ""
		if method.Pointer {
			prefix = "*"
		}
		result = "(" + prefix + r.typeName(method.ResultType) + ", error)"
	}
	fmt.Fprintf(b, "func (q *%s) %s(ctx context.Context%s) %s {\n", implementation, method.Name, param, result)
	fmt.Fprintf(b, "\tconst statement = %s\n", strconv.Quote(method.SQL))
	if method.ParamType != nil {
		b.WriteString("\tquery, args, err := sqlxgen.BindNamedIn(q.exec, statement, arg)\n")
	} else {
		b.WriteString("\tif _, err := sqlxgen.DetectDialect(q.exec); err != nil { ")
		switch method.Mode {
		case CustomExec:
			b.WriteString("return err")
		case CustomMany:
			b.WriteString("return nil, err")
		case CustomRowsAffected:
			b.WriteString("return 0, err")
		case CustomOne:
			if method.Pointer {
				b.WriteString("return nil, err")
			} else {
				fmt.Fprintf(b, "var zero %s; return zero, err", r.typeName(method.ResultType))
			}
		}
		b.WriteString(" }; query, args := q.exec.Rebind(statement), []any(nil); var err error\n")
	}
	switch method.Mode {
	case CustomExec:
		b.WriteString("\tif err != nil { return err }; _, err = q.exec.ExecContext(ctx, query, args...); return err\n}\n\n")
	case CustomRowsAffected:
		b.WriteString("\tif err != nil { return 0, err }; result, err := q.exec.ExecContext(ctx, query, args...); if err != nil { return 0, err }; return result.RowsAffected()\n}\n\n")
	case CustomMany:
		fmt.Fprintf(b, "\tif err != nil { return nil, err }; var result []%s; if err := sqlx.SelectContext(ctx, q.exec, &result, query, args...); err != nil { return nil, err }; return result, nil\n}\n\n", r.typeName(method.ResultType))
	case CustomOne:
		typeName := r.typeName(method.ResultType)
		if method.Pointer {
			fmt.Fprintf(b, "\tif err != nil { return nil, err }; var result %s; if err := sqlx.GetContext(ctx, q.exec, &result, query, args...); err != nil { return nil, err }; return &result, nil\n}\n\n", typeName)
		} else {
			fmt.Fprintf(b, "\tif err != nil { var zero %s; return zero, err }; var result %s; if err := sqlx.GetContext(ctx, q.exec, &result, query, args...); err != nil { var zero %s; return zero, err }; return result, nil\n}\n\n", typeName, typeName, typeName)
		}
	}
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
